### ISSUE TITLE
Tags are overlapping when resizing / margins

### ISSUE THREAD

**Issue by nebbles** [ImperialDyson/SummerShow2019#1]
Edge cases for resizing and margins cause tags to overlap and not render properly.

**Comment by paolofalcoruegg** [comment]
Used CSS flex properties to make tags stack when overflowing.

.tag-custom {
    font-size: 11px;
    letter-spacing: 1px;
    text-transform: uppercase;
    font-weight: 500;
    color: #AE9F9E;
    margin: 15px 0px 5px;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
}

.tag-custom span {
    background-color: #FED136;
    margin-top: 5px;
    margin-right: 5px;
    padding: 10px 10px;
    white-space: nowrap;
}
