### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by nebbles** [ImperialDyson/SummerShow2019#10]
The footer should be updated to be less prominent and hold key information.

**Comment by paolofalcoruegg** [comment]
Added social media links (checked and working)

**Comment by nebbles** [comment]
With https://github.com/ImperialDyson/SummerShow/commit/453992d95f2a37557a76072ff625f883fc4f2ef1 this issue is now closeable.

**Comment by nebbles** [comment]
The footer needs associated logos

- Imperial
- RCA
- DSDE
- Great Exhibition
- DesSoc

**Comment by nebbles** [comment]
Completed with e74a668657e460c8e6087ed4861be6d1af2832b3
