### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by nebbles** [ImperialDyson/SummerShow2019#13]
A bonus feature for the website. Would help to find projects by title, description, or author name.

**Comment by paolofalcoruegg** [comment]
We shall be using this package:

https://github.com/christian-fei/Simple-Jekyll-Search

**Comment by nebbles** [comment]
Assigned to @pa17 for initial implementation. Styling will be sorted by @nebbles and Clarisse later.

**Comment by paolofalcoruegg** [comment]
Done initial implementation. Outstanding issues include:

* mobile support
* search result appearance
* search bar appearance (could just be the magnifying glass until you click it)

**Comment by paolofalcoruegg** [comment]
Should work fine now
