### ISSUE TITLE
Projects order should be shuffled on load

### ISSUE THREAD

**Issue by nebbles** [ImperialDyson/SummerShow2019#6]
Functionality will probably need to be implemented into a JS script which reorders the elements on load. 

Jekyll builds statically and so does mot modify after build - so cant reshuffle.

**Comment by paolofalcoruegg** [comment]
Added randomisation with script found in _includes/randomize.html
The class 'randomize' needs to be added to the wrapper of items in ug/index.html, pg/index.html research/index.html. So far only in UG since only one with more than one item

**Comment by nebbles** [comment]
Noice - randomisation looks like it works (with only 3 projects there are 6 combinations which is why it seems like it sometimes isnt working) should probably just check this once we have more projects added

**Comment by paolofalcoruegg** [comment]
Refactored into randomise.js
