### ISSUE TITLE
Update SEO

### ISSUE THREAD

**Issue by nebbles** [ImperialDyson/SummerShow2019#8]
Page titles, subtitles, descriptions, and images should be utilised properly for SEO and for previews when link sharing.

Applies mainly to

- Homepage
- UG / PG / Research / About main pages
- *additionally double check it is done properly for projects*

**Comment by nebbles** [comment]
Suggested by Paolo: https://github.com/jekyll/jekyll-seo-tag

**Comment by paolofalcoruegg** [comment]
Added SEO through jekyll-seo-tag

**Comment by nebbles** [comment]
Fixed image src for url sharing. Will monitor SEO on production domain
